name: Main-Workflow

on:
  push:
    branches: [main]
  pull_request:

permissions: write-all

jobs:
  R-CMD-Check:
    if: ${{ !cancelled() }}
    uses: Open-Systems-Pharmacology/Workflows/.github/workflows/R-CMD-check-build.yaml@main
    secrets: inherit
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

  pkgdown:
    if: ${{ !cancelled() }}
    uses: Open-Systems-Pharmacology/Workflows/.github/workflows/pkgdown.yaml@main
    secrets: inherit
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
